name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmakeArgs: -G Ninja
          - os: windows-latest
            cmakeArgs: -G "NMake Makefiles" -DCMAKE_CXX_COMPILER=msvc


    steps:
      - uses: actions/checkout@v2

      - name: Create build directory
        run: cmake -E make_directory "${{ runner.workspace }}/build"

      - name: Configure CMake
        working-directory: ${{ runner.workspace }}/build
        run: cmake -S ${{ runner.workspace }} -B ${{ runner.workspace }}/build ${{ matrix.cmakeArgs }}

      - name: Run CMake Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build ${{ runner.workspace }}

      - name: Run Tests
        working-directory: ${{ runner.workspace }}/build
        run: ctest --output-on-failure
