name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmakeArgs: -G "Unix Makefiles"
          - os: windows-latest
            cmakeArgs: -G "Visual Studio 16 2019"


    steps:
      - uses: actions/checkout@v2

      - name: Create build directory
        run: cmake -E make_directory "${{ runner.workspace }}/build"

      - name: Configure CMake
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{ runner.workspace }}/build
        run: cmake -S $GITHUB_WORKSPACE -B ${{ runner.workspace }}/build ${{ matrix.cmakeArgs }}

      - name: Configure CMake
        if: matrix.os == 'windows-latest'
        working-directory: ${{ runner.workspace }}/build
        run: cmake -S ${env:GITHUB_WORKSPACE} -B ${{ runner.workspace }}/build ${{ matrix.cmakeArgs }}

      - name: Run CMake Build
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build $GITHUB_WORKSPACE

      - name: Run CMake Build
        if: matrix.os == 'windows-latest'
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build ${env:GITHUB_WORKSPACE}

      - name: Run Tests
        working-directory: ${{ runner.workspace }}/build
        run: ctest --output-on-failure
